[package]
name = "egui-font-search"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.27", features = ["default", "__screenshot"] }
font-kit = { version = "0.13", features = ["default"] }
